# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Structural Patterns' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Structural Patterns
pod 'AFNetworking', '~> 3.1.0' 
end
